trigger:
  branches:
    include:
      - master
  paths:
    include:
      - client

variables:
- group: az-credentials

pool:
  vmImage: ubuntu-latest 

steps:
- script: |
    npm update -g npm \
    npm install -g yarn 
  workingDirectory: $(Build.SourcesDirectory)/client
  displayName: Install Yarn

- script: yarn install
  workingDirectory: $(Build.SourcesDirectory)/client
  displayName: Install Yarn Packages

- script: yarn build
  workingDirectory: $(Build.SourcesDirectory)/client
  displayName: Build Static Assets

- script: az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
  displayName: Login to Azure using the AzureDevOps Service Principle
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

- script: az storage blob upload-batch -s ./dist -d '$web' --account-name $(SpaStorageAccountName) --overwrite=true
  workingDirectory: $(Build.SourcesDirectory)/client
  displayName: Copy static assets to Storage Account
