trigger: none

pool:
  vmImage: ubuntu-latest 

variables:
- group: az-credentials

steps:
- script: |
    terraform init -backend-config=backend.tfvars
  workingDirectory: $(Build.SourcesDirectory)/infrastructure/environments/dev
  displayName: Terraform Init
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

- script: |
    terraform destroy -auto-approve -var-file=variables.tfvars \
      -var "dns={\"custom_domain_verification_id\":\"$CUSTOM_DOMAIN_VERIFICATION_ID\"}" \
      -var "app_secrets={\"docker_registry_password\":\"$DOCKER_REGISTRY_PASSWORD\"}" \
      -var "database_credentials={\"admin_username\":\"$DB_ADMIN_USERNAME\", \"admin_password\":\"$DB_ADMIN_PASSWORD\"}"
  workingDirectory: $(Build.SourcesDirectory)/infrastructure/environments/dev
  displayName: Terraform Destroy (ignores drift) 
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
