name: "WebApiPipeline"

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - server

pool:
  vmImage: ubuntu-latest 

variables:
- group: az-credentials
- group: docker-hub

steps:
- script: dotnet build
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Build Solution

- script: dotnet test
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Run Tests

- script: docker build . -t newdevpleaseignore/fullstackonazure:latest
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Build Docker Image

- script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Docker Login

- script: docker image push newdevpleaseignore/fullstackonazure:latest
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Docker Push

