trigger:
  branches:
    include:
      - master
  paths:
    include:
      - server

pool:
  vmImage: ubuntu-latest 

variables:
- group: az-credentials
- group: docker-hub

steps:
- script: dotnet build
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Build Solution

- script: dotnet test
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Run Tests

- script: docker build . -t "newdevpleaseignore/fullstackonazure:$(Build.BuildNumber)" -t newdevpleaseignore/fullstackonazure:latest
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Build Docker Image

- script: echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Docker Login
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)
    DOCKER_TOKEN: $(DOCKER_PASSWORD)

- script: docker image push newdevpleaseignore/fullstackonazure --all-tags
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Docker Push

- script: az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
  displayName: Deploy image to azure webapp
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

- script: az webapp config container set --docker-custom-image-name "newdevpleaseignore/fullstackonazure:$(Build.BuildNumber)" --name $(WebAppName) --resource-group $(WebAppResourceGroup) 
  displayName: Deploy image to azure webapp
  
