name: "WebApiPipeline"

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - server

pool:
  vmImage: ubuntu-latest 

variables:
- group: az-credentials
- group: docker-hub

steps:
- script: dotnet build
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Build Solution

- script: dotnet test
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Run Tests

- script: docker build . -t newdevpleaseignore/fullstackonazure:$(Rev:r) -t newdevpleaseignore/fullstackonazure:latest
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Build Docker Image

- script: echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Docker Login
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)
    DOCKER_TOKEN: $(DOCKER_PASSWORD)

- script: docker image push newdevpleaseignore/fullstackonazure --all-tags
  workingDirectory: $(Build.SourcesDirectory)/server
  displayName: Docker Push

